version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    restart: on-failure
  jms:
    image: vromero/activemq-artemis
    ports:
      - "8161:8161"
      - "61616:61616"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  eureka:
    image: levphilippov89/mssc-eureka-server
    ports:
      - "8761:8761"
  config:
    image: levphilippov89/mssc-brewery-cloud-config:latest
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: true
  inventory:
      image: levphilippov89/mssc-beer-inventory-service:latest
      ports:
        - "8082:8082"
      depends_on:
        - eureka
        - config
        - zipkin
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
        EUREKA_INSTANCE_PREFER-IP-ADDRESS: true
        SPRING_PROFILES_ACTIVE: local-discovery,local
        SPRING_ZIPKIN_BASE-URL: http://zipkin:9411
        SPRING_ARTEMIS_HOST: jms
        LOGGING_LEVEL_GURU_SFG_BEER: debug

      restart: on-failure
      labels:
        collect_logs_with_filebeat: "true"
        decode_log_event_to_json_object: "true"
  failover:
    image: levphilippov89/mssc-inventory-failover
    ports:
      - "8083:8083"
    depends_on:
      - eureka
      - config
      - zipkin
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: true
      SPRING_ZIPKIN_BASE-URL: http://zipkin:9411
    restart: on-failure
  beer:
    image: levphilippov89/mssc_beer_service
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - config
      - zipkin
      - failover
      - inventory
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: true
      SPRING_PROFILES_ACTIVE: local-discovery, local, basic
      SFG_BREWERY_BEER-INVENTORY-SERVICE-URL: http://inventory:8082
      SPRING_ZIPKIN_BASE-URL: http://zipkin:9411
      SPRING_ARTEMIS_HOST: jms
      LOGGING_LEVEL_LEV_PHILIPPOV: debug
    restart: on-failure
  order:
    image: levphilippov89/mssc-beer-order-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - config
      - zipkin
      - beer
    environment:
      LOGGING_LEVEL_ROOT: info
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: true
      SPRING_PROFILES_ACTIVE: local-discovery,local
      SPRING_ZIPKIN_ENABLED: true
      SPRING_ZIPKIN_BASE-URL: http://zipkin:9411
      SPRING_ARTEMIS_HOST: jms
      SFG_BREWERY_BEER-SERVICE-HOST-URL: http://beer:8080
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  gateway:
    image: levphilippov89/mssc-brewery-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka
      - config
      - zipkin
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: true
      SPRING_PROFILES_ACTIVE: local-discovery
      SPRING_ZIPKIN_BASE-URL: http://zipkin:9411
      SPRING_SECURITY_USER_NAME: user
      SPRING_SECURITY_USER_PASSWORD: password
      LOGGING_LEVEL_GURU_SFG_BEER: debug

